import { TYPOGRAPHY, SPACING } from '../../constants';
import type { ThemeColors, ThemeShadows } from '../../theme';

const createImageModelsStylesPart1 = (colors: ThemeColors, shadows: ThemeShadows) => ({
  recToggle: {
    padding: 12,
    borderRadius: 16,
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.border,
    ...shadows.small,
  },
  recToggleActive: {
    backgroundColor: `${colors.primary}08`,
    borderColor: colors.primary,
  },
  recHint: {
    flexDirection: 'row' as const,
    alignItems: 'center' as const,
    gap: 8,
    paddingHorizontal: 16,
    paddingVertical: 12,
    marginBottom: 16,
    backgroundColor: `${colors.primary}05`,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: `${colors.primary}20`,
  },
  recHintText: {
    ...TYPOGRAPHY.meta,
    color: colors.textSecondary,
    flex: 1,
    lineHeight: 16,
  },
  imageModelsSection: {
    paddingHorizontal: 20,
  },
  imageModelsList: {
    paddingHorizontal: 20,
    marginBottom: 32,
  },
  recommendedBadge: {
    backgroundColor: colors.primary,
    alignSelf: 'flex-start' as const,
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderTopLeftRadius: 10,
    borderTopRightRadius: 10,
    marginLeft: 16,
    marginBottom: -1,
    zIndex: 1,
    ...shadows.small,
  },
  recommendedBadgeText: {
    ...TYPOGRAPHY.meta,
    color: '#FFFFFF',
    fontWeight: '800' as const,
    fontSize: 9,
    letterSpacing: 0.8,
    textTransform: 'uppercase' as const,
  },
  imageModelCard: { 
    marginBottom: 16,
    backgroundColor: colors.surface,
    borderRadius: 20,
    padding: 16,
    borderWidth: 1,
    borderColor: colors.borderLight,
    ...shadows.medium,
  },
  imageModelHeader: {
    flexDirection: 'row' as const,
    justifyContent: 'space-between' as const,
    alignItems: 'flex-start' as const,
    marginBottom: 12,
  },
  imageModelInfo: { flex: 1 },
  imageModelName: { 
    ...TYPOGRAPHY.h3, 
    color: colors.text, 
    marginBottom: 4,
    fontWeight: '700' as const,
  },
  imageModelDesc: { 
    ...TYPOGRAPHY.bodySmall, 
    color: colors.textSecondary, 
    marginBottom: 8,
    lineHeight: 18,
  },
  imageModelSize: { 
    ...TYPOGRAPHY.meta, 
    color: colors.textMuted,
    fontWeight: '600' as const,
  },
  activeBadge: {
    backgroundColor: `${colors.info}15`,
    paddingHorizontal: 12,
    paddingVertical: 4,
    borderRadius: 12,
    marginLeft: 8,
    borderWidth: 1,
    borderColor: `${colors.info}30`,
  },
  activeBadgeText: { 
    ...TYPOGRAPHY.meta, 
    color: colors.info,
    fontWeight: '700' as const,
  },
  imageModelActions: {
    flexDirection: 'row' as const,
    alignItems: 'center' as const,
    gap: 12,
    marginTop: 12,
    paddingTop: 12,
    borderTopWidth: 1,
    borderTopColor: colors.divider,
  },
  setActiveButton: {
    backgroundColor: `${colors.primary}15`,
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderRadius: 12,
    flex: 1,
    alignItems: 'center' as const,
  },
  setActiveButtonText: { 
    ...TYPOGRAPHY.bodySmall, 
    color: colors.primary,
    fontWeight: '700' as const,
  },
  deleteImageButton: { 
    padding: 10,
    borderRadius: 12,
    backgroundColor: `${colors.error}10`,
  },
  imageModelCompactRow: {
    flexDirection: 'row' as const,
    alignItems: 'center' as const,
    backgroundColor: colors.surface,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: colors.borderLight,
    paddingHorizontal: 16,
    paddingVertical: 12,
    marginBottom: 10,
    gap: 12,
    ...shadows.small,
  },
  imageModelCompactInfo: { flex: 1, gap: 2 },
  imageModelCompactName: { ...TYPOGRAPHY.bodySmall, color: colors.text, fontWeight: '700' as const },
  imageModelCompactMeta: { ...TYPOGRAPHY.metaSmall, color: colors.textMuted, fontWeight: '500' as const },
  activeBadgeCompact: {
    backgroundColor: `${colors.info}15`,
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: `${colors.info}20`,
  },
  activeBadgeCompactText: { ...TYPOGRAPHY.metaSmall, color: colors.info, fontWeight: '700' as const },
  setActiveButtonCompact: {
    backgroundColor: `${colors.primary}15`,
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 8,
  },
  setActiveButtonCompactText: { ...TYPOGRAPHY.metaSmall, color: colors.primary, fontWeight: '700' as const },
  deleteImageButtonCompact: { 
    padding: 6,
    borderRadius: 8,
    backgroundColor: `${colors.error}05`,
  },
  availableTitle: { 
    ...TYPOGRAPHY.meta, 
    color: colors.textMuted, 
    marginBottom: 12,
    fontWeight: '700' as const,
    textTransform: 'uppercase' as const,
    letterSpacing: 1,
  },
});

const createImageModelsStylesPart2 = (colors: ThemeColors, shadows: ThemeShadows) => ({
  downloadImageButton: {
    flexDirection: 'row' as const,
    alignItems: 'center' as const,
    justifyContent: 'center' as const,
    backgroundColor: colors.primary,
    paddingVertical: 12,
    paddingHorizontal: 20,
    borderRadius: 14,
    gap: 10,
    ...shadows.small,
  },
  downloadImageButtonText: { 
    ...TYPOGRAPHY.body, 
    color: '#FFFFFF',
    fontWeight: '700' as const,
  },
  imageDownloadProgress: { 
    alignItems: 'center' as const, 
    gap: 10,
    backgroundColor: `${colors.text}03`,
    padding: 16,
    borderRadius: 16,
  },
  imageDownloadText: { ...TYPOGRAPHY.bodySmall, color: colors.textSecondary, fontWeight: '600' as const },
  imageProgressBar: {
    width: '100%' as const,
    height: 10,
    backgroundColor: `${colors.text}08`,
    borderRadius: 5,
    overflow: 'hidden' as const,
  },
  imageProgressFill: {
    height: '100%' as const,
    backgroundColor: colors.primary,
    borderRadius: 5,
  },
  allDownloadedText: {
    ...TYPOGRAPHY.bodySmall,
    color: colors.textMuted,
    textAlign: 'center' as const,
    paddingVertical: 24,
    fontStyle: 'italic' as const,
  },
  hfLoadingContainer: {
    flexDirection: 'row' as const,
    alignItems: 'center' as const,
    justifyContent: 'center' as const,
    gap: 12,
    paddingVertical: 40,
  },
  hfErrorContainer: { 
    alignItems: 'center' as const, 
    paddingVertical: 40, 
    gap: 16,
    backgroundColor: `${colors.error}05`,
    borderRadius: 24,
    marginHorizontal: 20,
    borderWidth: 1,
    borderColor: `${colors.error}10`,
  },
  hfErrorText: { ...TYPOGRAPHY.body, color: colors.error, textAlign: 'center' as const, paddingHorizontal: 20 },
  retryButton: {
    backgroundColor: colors.primary,
    paddingHorizontal: 24,
    paddingVertical: 12,
    borderRadius: 14,
    ...shadows.small,
  },
  retryButtonText: { ...TYPOGRAPHY.bodySmall, color: '#FFFFFF', fontWeight: '700' as const },
  textModelsSectionTitle: { 
    ...TYPOGRAPHY.h2, 
    color: colors.text, 
    marginBottom: 16, 
    marginTop: 8,
    letterSpacing: -0.5,
  },
  imageSearchRow: {
    flexDirection: 'row' as const,
    alignItems: 'center' as const,
    gap: 12,
    marginBottom: 16,
  },
  imageSearchInput: {
    ...TYPOGRAPHY.body,
    flex: 1,
    backgroundColor: colors.surface,
    borderRadius: 16,
    paddingHorizontal: 16,
    paddingVertical: 12,
    color: colors.text,
    borderWidth: 1,
    borderColor: colors.border,
  },
  backendFilterRow: { flexDirection: 'row' as const, gap: 10, marginBottom: 16 },
  modelNameRow: {
    flexDirection: 'row' as const,
    alignItems: 'center' as const,
    gap: 10,
    marginBottom: 6,
  },
  badgeRow: { flexDirection: 'row' as const, gap: 8, marginBottom: 8 },
  backendBadge: { 
    paddingHorizontal: 10, 
    paddingVertical: 3, 
    borderRadius: 8,
    borderWidth: 1,
  },
  gpuBadge: { 
    backgroundColor: `${colors.primary}10`,
    borderColor: `${colors.primary}20`,
  },
  npuBadge: { 
    backgroundColor: '#FF990015',
    borderColor: '#FF990030',
  },
  backendBadgeText: { 
    ...TYPOGRAPHY.labelSmall, 
    color: colors.text,
    fontWeight: '700' as const,
  },
  variantBadge: {
    backgroundColor: `${colors.text}08`,
    paddingHorizontal: 10,
    paddingVertical: 3,
    borderRadius: 8,
  },
  variantBadgeText: { 
    ...TYPOGRAPHY.labelSmall, 
    color: colors.textSecondary,
    fontWeight: '600' as const,
  },
  variantHint: { 
    ...TYPOGRAPHY.labelSmall, 
    color: colors.textMuted, 
    marginBottom: 4,
    fontWeight: '500' as const,
  },
});

export const createImageModelsStyles = (colors: ThemeColors, shadows: ThemeShadows) => ({
  ...createImageModelsStylesPart1(colors, shadows),
  ...createImageModelsStylesPart2(colors, shadows),
});
