/* eslint-disable max-lines */
import { TYPOGRAPHY, SPACING } from '../../constants';
import type { ThemeColors, ThemeShadows } from '../../theme';
import { createImageModelsStyles } from './imageStyles';

const createBaseStyles = (colors: ThemeColors, shadows: ThemeShadows) => ({
  flex1: { flex: 1 },
  backButton: { 
    padding: 8, 
    marginRight: 8,
    borderRadius: 12,
    backgroundColor: `${colors.text}08`,
  },
  searchContainerNoPadding: { paddingHorizontal: 0 },
  container: { flex: 1, backgroundColor: colors.background },
  header: {
    paddingHorizontal: SPACING.lg,
    paddingTop: SPACING.lg,
    paddingBottom: SPACING.md,
    backgroundColor: colors.background,
  },
  headerRow: {
    flexDirection: 'row' as const,
    justifyContent: 'space-between' as const,
    alignItems: 'center' as const,
    marginBottom: SPACING.lg,
  },
  title: { 
    ...TYPOGRAPHY.h1, 
    color: colors.text, 
    letterSpacing: -0.5,
  },
  downloadManagerButton: { 
    padding: 10, 
    borderRadius: 14,
    backgroundColor: `${colors.text}08`,
    position: 'relative' as const,
  },
  downloadBadge: {
    position: 'absolute' as const,
    top: -4,
    right: -4,
    backgroundColor: colors.primary,
    borderRadius: 10,
    minWidth: 20,
    height: 20,
    alignItems: 'center' as const,
    justifyContent: 'center' as const,
    borderWidth: 2,
    borderColor: colors.background,
    paddingHorizontal: 4,
    ...shadows.small,
  },
  downloadBadgeText: { 
    ...TYPOGRAPHY.labelSmall, 
    color: '#FFFFFF',
    fontWeight: '800' as const,
  },
  tabBarOutline: {
    backgroundColor: `${colors.text}05`,
    borderRadius: 16,
    padding: 4,
    marginHorizontal: SPACING.lg,
    marginBottom: SPACING.lg,
    flexDirection: 'row' as const,
  },
  tabItem: { 
    flex: 1,
    paddingVertical: 10, 
    alignItems: 'center' as const,
    justifyContent: 'center' as const,
    borderRadius: 12,
    position: 'relative' as const,
    backgroundColor: 'transparent' as const,
    borderWidth: 1,
    borderColor: 'transparent',
  },
  tabText: { 
    ...TYPOGRAPHY.bodySmall, 
    color: colors.textMuted,
    fontWeight: '600' as const,
  },
  // Colores específicos solicitados para la animación
  tabActiveBg: '#333333' as any,
  tabInactiveBorder: '#666666' as any,
  tabActiveText: '#FFFFFF' as any,
  tabInactiveText: colors.textMuted as any,

  imageTabContent: { flex: 1 },
  searchContainer: {
    flexDirection: 'row' as const,
    alignItems: 'center' as const,
    paddingHorizontal: 20,
    paddingBottom: 20,
    gap: 12,
  },
  searchInputWrapper: {
    flex: 1,
    flexDirection: 'row' as const,
    alignItems: 'center' as const,
    backgroundColor: colors.surface,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: colors.border,
    paddingHorizontal: 16,
    ...shadows.small,
  },
  searchIcon: {
    marginRight: 8,
  },
  searchInput: {
    ...TYPOGRAPHY.body,
    flex: 1,
    paddingVertical: 12,
    color: colors.text,
  },
  importButton: {
    flexDirection: 'row' as const,
    alignItems: 'center' as const,
    justifyContent: 'center' as const,
    gap: 10,
    marginHorizontal: 20,
    marginTop: 8,
    marginBottom: 16,
    paddingVertical: 16,
    borderWidth: 1.5,
    borderStyle: 'dashed' as const,
    borderColor: `${colors.primary}40`,
    borderRadius: 20,
    backgroundColor: `${colors.primary}08`,
  },
  importButtonText: { 
    ...TYPOGRAPHY.body, 
    color: colors.primary,
    fontWeight: '600' as const,
  },
  importProgressCard: {
    marginHorizontal: 20,
    marginTop: 12,
    marginBottom: 16,
    padding: 20,
    backgroundColor: colors.surface,
    borderRadius: 20,
    ...shadows.medium,
    gap: 12,
  },
  importProgressHeader: {
    flexDirection: 'row' as const,
    alignItems: 'center' as const,
    gap: 10,
  },
  importProgressText: { ...TYPOGRAPHY.bodySmall, color: colors.text, flex: 1, fontWeight: '600' as const },
  importProgressPercent: { ...TYPOGRAPHY.meta, color: colors.textMuted, textAlign: 'center' as const },
  progressBar: {
    width: '100%' as const,
    height: 6,
    backgroundColor: `${colors.primary}20`,
    borderRadius: 3,
    overflow: 'hidden' as const,
  },
  progressFill: {
    height: '100%' as const,
    backgroundColor: colors.primary,
  },
  loadingContainer: {
    flex: 1,
    justifyContent: 'center' as const,
    alignItems: 'center' as const,
    gap: 20,
  },
  loadingText: { ...TYPOGRAPHY.body, color: colors.textSecondary },
  listContent: { paddingHorizontal: 20, paddingBottom: 40 },
  deviceBanner: {
    backgroundColor: `${colors.primary}08`,
    borderRadius: 16,
    paddingHorizontal: 16,
    paddingVertical: 12,
    marginBottom: 24,
    flexDirection: 'row' as const,
    alignItems: 'center' as const,
    gap: 12,
    borderWidth: 1,
    borderColor: `${colors.primary}20`,
  },
  deviceBannerText: { ...TYPOGRAPHY.meta, color: colors.primary, flex: 1, lineHeight: 18 },
  deviceBannerWarning: { color: colors.error, marginTop: 4 },
  emptyCard: { 
    alignItems: 'center' as const, 
    padding: 40,
    backgroundColor: `${colors.text}03`,
    borderRadius: 24,
    marginTop: 20,
  },
  emptyText: { ...TYPOGRAPHY.body, color: colors.textSecondary, textAlign: 'center' as const, marginTop: 12 },
});

const createFilterStyles = (colors: ThemeColors, _shadows: ThemeShadows) => ({
  filterBar: { marginBottom: 12, paddingBottom: 4 },
  filterPillRow: {
    paddingHorizontal: 20,
    gap: 10,
    alignItems: 'center' as const,
  },
  filterPill: {
    flexDirection: 'row' as const,
    alignItems: 'center' as const,
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: 12,
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.border,
    gap: 6,
  },
  filterPillActive: { 
    backgroundColor: `${colors.primary}12`, 
    borderColor: colors.primary,
  },
  filterPillText: { 
    ...TYPOGRAPHY.bodySmall, 
    color: colors.textSecondary,
    fontWeight: '500' as const,
  },
  filterPillTextActive: { 
    color: colors.primary,
    fontWeight: '600' as const,
  },
  filterCountBadge: {
    backgroundColor: colors.primary,
    borderRadius: 8,
    minWidth: 18,
    height: 18,
    alignItems: 'center' as const,
    justifyContent: 'center' as const,
    paddingHorizontal: 4,
  },
  filterCountText: { 
    ...TYPOGRAPHY.labelSmall, 
    color: '#FFFFFF', 
    fontWeight: '800' as const,
  },
  clearFiltersButton: { 
    paddingHorizontal: 12, 
    paddingVertical: 8,
  },
  clearFiltersText: { 
    ...TYPOGRAPHY.bodySmall, 
    color: colors.error,
    fontWeight: '600' as const,
  },
  filterExpandedContent: { 
    paddingHorizontal: 20, 
    paddingTop: 8, 
    paddingBottom: 4,
  },
  filterChipWrap: { 
    flexDirection: 'row' as const, 
    flexWrap: 'wrap' as const, 
    gap: 10,
  },
  filterChip: {
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: 12,
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.border,
  },
  filterChipActive: { 
    backgroundColor: `${colors.primary}12`, 
    borderColor: colors.primary,
  },
  filterChipText: { 
    ...TYPOGRAPHY.bodySmall, 
    color: colors.textSecondary,
  },
  filterChipTextActive: { 
    color: colors.primary,
    fontWeight: '600' as const,
  },
  filterToggle: { 
    padding: 12, 
    borderRadius: 16, 
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.border,
  },
  filterToggleActive: { 
    backgroundColor: `${colors.primary}08`,
    borderColor: colors.primary,
  },
  filterDot: {
    position: 'absolute' as const,
    top: 6,
    right: 6,
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: colors.primary,
    borderWidth: 1,
    borderColor: colors.background,
  },
});

const createTextModelsStyles = (colors: ThemeColors, shadows: ThemeShadows) => ({
  modelInfoCard: { 
    marginHorizontal: 20, 
    marginTop: 12, 
    marginBottom: 20,
    borderRadius: 20,
    padding: 20,
    backgroundColor: colors.surface,
    ...shadows.medium,
  },
  authorRow: {
    flexDirection: 'row' as const,
    alignItems: 'center' as const,
    marginBottom: 10,
    gap: 10,
  },
  modelAuthor: { 
    ...TYPOGRAPHY.body, 
    color: colors.textSecondary,
    fontWeight: '600' as const,
  },
  credibilityBadge: {
    flexDirection: 'row' as const,
    alignItems: 'center' as const,
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 8,
    gap: 6,
  },
  credibilityIcon: { ...TYPOGRAPHY.labelSmall },
  credibilityText: { ...TYPOGRAPHY.meta, fontWeight: '700' as const },
  modelDescription: { 
    ...TYPOGRAPHY.body, 
    color: colors.text, 
    marginBottom: 16,
    lineHeight: 22,
  },
  modelStats: { 
    flexDirection: 'row' as const, 
    gap: 20,
    borderTopWidth: 1,
    borderTopColor: colors.borderLight,
    paddingTop: 16,
  },
  statText: { 
    ...TYPOGRAPHY.meta, 
    color: colors.textMuted,
    fontWeight: '500' as const,
  },
  sectionTitle: { 
    ...TYPOGRAPHY.h3, 
    color: colors.text, 
    paddingHorizontal: 20, 
    marginBottom: 6,
    marginTop: 8,
  },
  sectionSubtitle: {
    ...TYPOGRAPHY.bodySmall,
    color: colors.textSecondary,
    paddingHorizontal: 20,
    marginBottom: 20,
  },
  recommendedTitle: { 
    ...TYPOGRAPHY.meta, 
    color: colors.textMuted, 
    marginBottom: 12,
    fontWeight: '700' as const,
    textTransform: 'uppercase' as const,
    letterSpacing: 1,
  },
});

export const createStyles = (colors: ThemeColors, shadows: ThemeShadows) => ({
  ...createBaseStyles(colors, shadows),
  ...createFilterStyles(colors, shadows),
  ...createTextModelsStyles(colors, shadows),
  ...createImageModelsStyles(colors, shadows),
});
