import type { ThemeColors, ThemeShadows } from '../../theme';
import { TYPOGRAPHY } from '../../constants';
import { createRemoteStyles } from './remoteStyles';

export const createStyles = (colors: ThemeColors, _shadows: ThemeShadows) => ({
  tabBarOutline: {
    backgroundColor: `${colors.text}05`,
    borderRadius: 16,
    padding: 4,
    marginHorizontal: 16,
    marginTop: 12,
    marginBottom: 8,
    flexDirection: 'row' as const,
  },
  tabItem: { 
    flex: 1,
    paddingVertical: 10, 
    alignItems: 'center' as const,
    justifyContent: 'center' as const,
    borderRadius: 12,
    position: 'relative' as const,
    backgroundColor: 'transparent' as const,
  },
  tabText: { 
    ...TYPOGRAPHY.bodySmall, 
    color: colors.textMuted,
    fontWeight: '600' as const,
  },
  tabActiveBg: colors.background,
  tabActiveText: colors.text,
  tabInactiveText: colors.textMuted,

  loadingBanner: {
    flexDirection: 'row' as const,
    alignItems: 'center' as const,
    justifyContent: 'center' as const,
    backgroundColor: `${colors.primary}10`,
    paddingVertical: 10,
    gap: 10,
  },
  loadingText: {
    ...TYPOGRAPHY.bodySmall,
    color: colors.primary,
    fontWeight: '600' as const,
  },
  content: {
    paddingHorizontal: 16,
  },
  contentContainer: {
    paddingBottom: 24,
  },
  loadedSection: {
    marginBottom: 20,
    backgroundColor: `${colors.success}08`,
    borderRadius: 16,
    padding: 16,
    borderWidth: 1,
    borderColor: `${colors.success}20`,
  },
  loadedSectionImage: {
    backgroundColor: `${colors.info}08`,
    borderColor: `${colors.info}20`,
  },
  loadedHeader: {
    flexDirection: 'row' as const,
    alignItems: 'center' as const,
    gap: 8,
    marginBottom: 12,
  },
  loadedLabel: {
    ...TYPOGRAPHY.label,
    color: colors.success,
    fontWeight: '700' as const,
    textTransform: 'uppercase' as const,
  },
  loadedModelItem: {
    flexDirection: 'row' as const,
    alignItems: 'center' as const,
  },
  loadedModelInfo: {
    flex: 1,
  },
  loadedModelName: {
    ...TYPOGRAPHY.body,
    color: colors.text,
    fontWeight: '700' as const,
    marginBottom: 2,
  },
  loadedModelMeta: {
    ...TYPOGRAPHY.meta,
    color: colors.textMuted,
  },
  unloadButton: {
    flexDirection: 'row' as const,
    alignItems: 'center' as const,
    paddingVertical: 8,
    paddingHorizontal: 12,
    borderRadius: 10,
    backgroundColor: `${colors.error}10`,
    gap: 6,
  },
  unloadButtonText: {
    ...TYPOGRAPHY.bodySmall,
    color: colors.error,
    fontWeight: '600' as const,
  },
  sectionHeaderRow: {
    flexDirection: 'row' as const,
    alignItems: 'center' as const,
    marginBottom: 12,
    marginTop: 8,
    gap: 8,
  },
  sectionTitle: {
    ...TYPOGRAPHY.label,
    color: colors.textMuted,
    fontWeight: '700' as const,
    textTransform: 'uppercase' as const,
  },
  sectionSubTitle: {
    ...TYPOGRAPHY.meta,
    color: colors.textMuted,
    fontWeight: '600' as const,
  },
  emptyState: {
    alignItems: 'center' as const,
    paddingVertical: 40,
    gap: 12,
  },
  emptyTitle: {
    ...TYPOGRAPHY.h3,
    color: colors.text,
  },
  emptyText: {
    ...TYPOGRAPHY.bodySmall,
    color: colors.textMuted,
    textAlign: 'center' as const,
  },
  modelItem: {
    flexDirection: 'row' as const,
    alignItems: 'center' as const,
    padding: 16,
    borderRadius: 16,
    marginBottom: 8,
    backgroundColor: `${colors.text}03`,
    borderWidth: 1,
    borderColor: `${colors.text}05`,
  },
  modelItemSelected: {
    backgroundColor: `${colors.primary}08`,
    borderColor: `${colors.primary}30`,
  },
  modelItemSelectedRemote: {
    backgroundColor: `${colors.warning}08`,
    borderColor: `${colors.warning}30`,
  },
  modelItemSelectedImage: {
    backgroundColor: `${colors.info}08`,
    borderColor: `${colors.info}30`,
  },
  modelInfo: {
    flex: 1,
  },
  modelName: {
    ...TYPOGRAPHY.body,
    color: colors.text,
    fontWeight: '600' as const,
    marginBottom: 4,
  },
  modelNameSelected: {
    color: colors.primary,
  },
  modelNameSelectedRemote: {
    color: colors.warning,
  },
  modelNameSelectedImage: {
    color: colors.info,
  },
  modelMeta: {
    flexDirection: 'row' as const,
    alignItems: 'center' as const,
    flexWrap: 'wrap' as const,
    gap: 8,
  },
  modelSize: {
    ...TYPOGRAPHY.meta,
    color: colors.textMuted,
  },
  metaSeparator: {
    ...TYPOGRAPHY.meta,
    color: colors.textMuted,
    opacity: 0.5,
  },
  modelQuant: {
    ...TYPOGRAPHY.meta,
    color: colors.textMuted,
  },
  remoteBadge: {
    ...TYPOGRAPHY.meta,
    color: colors.warning,
    fontWeight: '700' as const,
    backgroundColor: `${colors.warning}15`,
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 4,
  },
  toolBadge: {
    backgroundColor: `${colors.warning}15`,
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 4,
  },
  thinkingBadge: {
    flexDirection: 'row' as const,
    alignItems: 'center' as const,
    backgroundColor: '#8B5CF615',
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 4,
    gap: 4,
  },
  thinkingBadgeText: {
    ...TYPOGRAPHY.label,
    color: '#8B5CF6',
    fontSize: 9,
  },
  visionBadge: {
    flexDirection: 'row' as const,
    alignItems: 'center' as const,
    backgroundColor: `${colors.info}15`,
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 4,
    gap: 4,
  },
  visionBadgeText: {
    ...TYPOGRAPHY.label,
    color: colors.info,
    fontSize: 9,
  },
  checkmark: {
    width: 24,
    height: 24,
    borderRadius: 12,
    backgroundColor: colors.primary,
    alignItems: 'center' as const,
    justifyContent: 'center' as const,
  },
  checkmarkRemote: {
    width: 24,
    height: 24,
    borderRadius: 12,
    backgroundColor: colors.warning,
    alignItems: 'center' as const,
    justifyContent: 'center' as const,
  },
  checkmarkImage: {
    width: 24,
    height: 24,
    borderRadius: 12,
    backgroundColor: colors.info,
    alignItems: 'center' as const,
    justifyContent: 'center' as const,
  },
  importModelItem: {
    flexDirection: 'row' as const,
    alignItems: 'center' as const,
    padding: 16,
    borderRadius: 16,
    marginBottom: 16,
    backgroundColor: `${colors.info}05`,
    borderWidth: 1,
    borderStyle: 'dashed' as const,
    borderColor: `${colors.info}30`,
    gap: 12,
  },
  importModelText: {
    ...TYPOGRAPHY.bodySmall,
    fontWeight: '700' as const,
    color: colors.info,
  },
  importModelIcon: {
    width: 32,
    height: 32,
    borderRadius: 10,
    backgroundColor: `${colors.info}15`,
    alignItems: 'center' as const,
    justifyContent: 'center' as const,
  },
  switchModelRow: {
    flexDirection: 'row' as const,
    justifyContent: 'space-between' as const,
    alignItems: 'center' as const,
    marginBottom: 8,
  },
  addServerInline: {
    flexDirection: 'row' as const,
    alignItems: 'center' as const,
    gap: 4,
    padding: 6,
    borderRadius: 8,
    backgroundColor: `${colors.primary}08`,
  },
  addServerInlineText: {
    ...TYPOGRAPHY.meta,
    color: colors.primary,
    fontWeight: '700' as const,
  },
});

export const createAllStyles = (colors: ThemeColors, shadows: ThemeShadows) => ({
  ...createStyles(colors, shadows),
  ...createRemoteStyles(colors, shadows),
});
