import type { ThemeColors, ThemeShadows } from '../theme';
import { TYPOGRAPHY } from '../constants';

export const createStyles = (colors: ThemeColors, shadows: ThemeShadows) => ({
  card: {
    backgroundColor: colors.surface,
    borderRadius: 20,
    padding: 16,
    marginBottom: 16,
    borderWidth: 1,
    borderColor: colors.borderLight,
    ...shadows.medium,
  },
  cardCompact: {
    padding: 14,
    marginBottom: 12,
    borderRadius: 18,
  },
  compactTopRow: {
    flexDirection: 'row' as const,
    alignItems: 'center' as const,
    marginBottom: 6,
    gap: 8,
  },
  compactNameGroup: {
    flexDirection: 'row' as const,
    alignItems: 'center' as const,
    flex: 1,
    gap: 8,
    minWidth: 0,
  },
  compactName: {
    flexShrink: 1,
    fontWeight: '700' as const,
  },
  authorTag: {
    backgroundColor: `${colors.text}08`,
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 8,
    flexShrink: 0,
  },
  authorTagText: {
    ...TYPOGRAPHY.metaSmall,
    color: colors.textSecondary,
    fontWeight: '600' as const,
  },
  cardActive: {
    borderColor: colors.primary,
    borderWidth: 1.5,
    backgroundColor: `${colors.primary}05`,
  },
  cardIncompatible: {
    opacity: 0.6,
  },
  header: {
    flexDirection: 'row' as const,
    justifyContent: 'space-between' as const,
    alignItems: 'flex-start' as const,
    marginBottom: 12,
  },
  headerCompact: {
    marginBottom: 6,
  },
  titleContainer: {
    flex: 1,
  },
  name: {
    ...TYPOGRAPHY.h3,
    color: colors.text,
    fontWeight: '700' as const,
    letterSpacing: -0.2,
  },
  author: {
    ...TYPOGRAPHY.bodySmall,
    color: colors.textSecondary,
    fontWeight: '500' as const,
  },
  authorRow: {
    flexDirection: 'row' as const,
    alignItems: 'center' as const,
    marginTop: 6,
    marginBottom: 8,
    gap: 8,
  },
  credibilityBadge: {
    flexDirection: 'row' as const,
    alignItems: 'center' as const,
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 6,
    gap: 4,
  },
  credibilityIcon: {
    ...TYPOGRAPHY.meta,
    fontSize: 10,
    fontWeight: '900' as const,
  },
  credibilityText: {
    ...TYPOGRAPHY.meta,
    fontWeight: '700' as const,
    fontSize: 10,
  },
  activeBadge: {
    backgroundColor: colors.primary,
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 8,
    ...shadows.small,
  },
  activeBadgeText: {
    ...TYPOGRAPHY.meta,
    color: '#FFFFFF',
    fontWeight: '800' as const,
  },
  description: {
    ...TYPOGRAPHY.bodySmall,
    color: colors.textSecondary,
    marginBottom: 16,
    lineHeight: 18,
  },
  descriptionCompact: {
    marginBottom: 8,
    ...TYPOGRAPHY.meta,
    color: colors.textSecondary,
    lineHeight: 16,
  },
  cardRow: {
    flexDirection: 'row' as const,
    alignItems: 'flex-start' as const,
    marginTop: 4,
  },
  cardContent: {
    flex: 1,
  },
  infoRow: {
    flexDirection: 'row' as const,
    flexWrap: 'wrap' as const,
    gap: 8,
  },
  infoRowCompact: {
    marginTop: 6,
    marginBottom: 8,
  },
  infoBadge: {
    backgroundColor: `${colors.text}05`,
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: colors.borderLight,
  },
  sizeBadge: {
    backgroundColor: `${colors.primary}08`,
    borderColor: `${colors.primary}20`,
  },
  infoText: {
    ...TYPOGRAPHY.meta,
    color: colors.textSecondary,
    fontWeight: '600' as const,
  },
  recommendedBadge: {
    backgroundColor: `${colors.info}15`,
    borderColor: `${colors.info}30`,
  },
  recommendedText: {
    color: colors.info,
    fontWeight: '700' as const,
  },
  warningBadge: {
    backgroundColor: `${colors.warning}15`,
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: `${colors.warning}30`,
  },
  warningText: {
    ...TYPOGRAPHY.meta,
    color: colors.warning,
    fontWeight: '700' as const,
  },
  visionBadge: {
    backgroundColor: `${colors.info}15`,
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: `${colors.info}30`,
  },
  visionText: {
    ...TYPOGRAPHY.meta,
    color: colors.info,
    fontWeight: '700' as const,
  },
  codeBadge: {
    backgroundColor: `${colors.warning}15`,
    borderColor: `${colors.warning}30`,
  },
  codeText: {
    ...TYPOGRAPHY.meta,
    color: colors.warning,
    fontWeight: '700' as const,
  },
  statsRow: {
    flexDirection: 'row' as const,
    gap: 16,
    marginBottom: 14,
    borderTopWidth: 1,
    borderTopColor: colors.divider,
    paddingTop: 12,
  },
  statsText: {
    ...TYPOGRAPHY.meta,
    color: colors.textMuted,
    fontWeight: '600' as const,
  },
  progressSection: {
    marginBottom: 14,
    backgroundColor: `${colors.text}03`,
    padding: 12,
    borderRadius: 14,
  },
  progressContainer: {
    flexDirection: 'row' as const,
    alignItems: 'center' as const,
    gap: 12,
  },
  progressBar: {
    flex: 1,
    height: 10,
    backgroundColor: `${colors.text}08`,
    borderRadius: 5,
    overflow: 'hidden' as const,
  },
  progressFill: {
    height: '100%' as const,
    backgroundColor: colors.primary,
    borderRadius: 5,
  },
  progressText: {
    ...TYPOGRAPHY.meta,
    color: colors.textSecondary,
    width: 44,
    textAlign: 'right' as const,
    fontWeight: '800' as const,
  },
  progressBytesText: {
    ...TYPOGRAPHY.meta,
    color: colors.textMuted,
    marginTop: 6,
    fontWeight: '500' as const,
  },
  iconButton: {
    padding: 8,
    borderRadius: 12,
    backgroundColor: `${colors.text}05`,
    marginLeft: 10,
  },
});
